name: ParseC++ Testing CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Catch2
      working-directory: ./tests/Catch2
      run: |
        cmake -Bbuild -H. -DBUILD_TESTING=OFF
        sudo cmake --build build/ --target install
    - name: Build
      run: |
        cmake -DENABLE_TESTING=ON .
        cmake --build .
    - name: Test
      run: ctest .